name: Approval Workflow

on:
  workflow_dispatch:
    inputs:
      approval_required:
        description: 'Approval Required'
        required: true
        default: 'false'

jobs:
  main_workflow:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.approval_required == 'true' }}
    steps:
      - name: Check for Approval
        uses: actions/github-script@v4
        with:
          script: |
            const { data: approvals } = await octokit.request('GET /repos/{owner}/{repo}/actions/runs/{run_id}/approvals', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId
            });

            if (approvals.total_count < 1) {
              core.setFailed('Approval not received within 10 minutes.');
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}